#!/bin/bash

# To enable pre-commit validation, copy that file to `.git/hooks/`

flutter analyze

dart fix --apply

dart format --set-exit-if-changed .

flutter test

status=$?
if [ $status -ne 0 ]; then
  echo "Code checks or build process failed. Please fix the issues before committing."
  exit $status
fi
exit 0