#!/bin/bash

# RUN: dart run grinder install-git-hooks

status=0

dart run grinder test
status_test=$?

echo " "
echo "Summary:"

if [ $status_test -ne 0 ]; then
  echo "[x] dart run grinder test - failed."
  status=1
else
  echo "[+] dart run grinder test - passed."
fi

if [ $status -ne 0 ]; then
  echo "ERROR: Checks failures above and fix before pushing."
fi

exit $status