// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions? get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
      case TargetPlatform.linux:
      default:
        return null;
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAT_5Ji7Mvj4ml1cSHpqJ_su2SLoJ_zgQI',
    appId: '1:637490835303:web:71916a85b5ba3e79c689c2',
    messagingSenderId: '637490835303',
    projectId: 'fingram-9030a',
    authDomain: 'fingram-9030a.firebaseapp.com',
    storageBucket: 'fingram-9030a.appspot.com',
    measurementId: 'G-3170SMMEH8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1b_6-j5yF2-IHc_hgbCJEym_s6ZTo1fM',
    appId: '1:637490835303:android:5e056fa931de68bac689c2',
    messagingSenderId: '637490835303',
    projectId: 'fingram-9030a',
    storageBucket: 'fingram-9030a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDL6lNmRUV3hw9o5RGA-IopdV631cFEcYw',
    appId: '1:637490835303:ios:750aa49a672e8d4fc689c2',
    messagingSenderId: '637490835303',
    projectId: 'fingram-9030a',
    storageBucket: 'fingram-9030a.appspot.com',
    iosClientId:
        '637490835303-54nnsjspk2nrht9cpaqnfoc0qrvg6fhu.apps.googleusercontent.com',
    iosBundleId: 'com.example.appFinance',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDL6lNmRUV3hw9o5RGA-IopdV631cFEcYw',
    appId: '1:637490835303:ios:c94c2442c25eae90c689c2',
    messagingSenderId: '637490835303',
    projectId: 'fingram-9030a',
    storageBucket: 'fingram-9030a.appspot.com',
    iosClientId:
        '637490835303-ls93eg7028hj0rbtc6ioselm4h60q07p.apps.googleusercontent.com',
    iosBundleId: 'com.example.appFinance.RunnerTests',
  );
}
