// Copyright 2023 The terCAD team. All rights reserved.
// Use of this source code is governed by a CC BY-NC-ND 4.0 license that can be
// found in the LICENSE file.

import 'dart:io';
import 'package:path/path.dart' as path;
import 'package:grinder/grinder.dart';
import './localization.dart' as locale;
import './coverage_badge.dart' as badge;
import './coverage.dart' as coverage;

main(args) => grind(args);

@DefaultTask()
void defaultTask() {
  log('Run `dart run grinder -h` to view the list');
  log('Run `dart run grinder <taskName>` to execute the task');
}

@Task('Generate file with all lib/**.dart-files included')
fullCoverage() {
  List<String> files = [];
  String content = "// AUTOGENERATED BY `dart run grinder full-coverage` \n";
  final rootFolder = Directory('${Directory.current.path}/lib');
  coverage.scanDirectory(rootFolder, rootFolder, files);
  for (var file in files) {
    content += "import 'package:app_finance$file';\n";
  }
  content += "void main() {}\n";
  File(path.join(Directory.current.path, 'test/_coverage.dart'))
      .writeAsStringSync(content);
}

@Task('Add Coverage Badge to README.md file')
coverageBadge() {
  final lineCoverage = badge.calculateLineCoverage(File('coverage/lcov.info'));
  badge.generateBadge('${Directory.current.path}/coverage', lineCoverage);
}

@Task('Install Git Hooks')
installGitHooks() {
  final currDir = Directory('./');
  final hookDir = Directory('./.git/hooks');
  final hookNames = ['pre-commit', 'pre-push'];
  for (final name in hookNames) {
    log('Applying: $name');
    final sourceFile = File(path.join(currDir.absolute.path, name));
    sourceFile.copySync(path.join(hookDir.absolute.path, name));
  }
  log('Git Hooks applied!');
}

@Task('Update Translations by sorting values alphabetically')
sortTranslations() {
  TaskArgs args = context.invocation.arguments;
  bool isQuiet = args.getFlag('quiet');
  bool isChanged = locale.sortArbKeys('./lib/l10n');
  if (isChanged && !isQuiet) {
    fail('Changes detected');
  }
}

@Task('Export Translations')
exportTranslations() {
  log('TBD: Messages extracted successfully');
}

@Task('Update Localized Files')
importTranslations() {
  log('TBD: Localized files generated successfully');
}
