name: Build AppImage Package

on:
  workflow_call:
    inputs:
      upload_url:
        description: "Release page URL"
        type: string
      version:
        description: "Latest tag name"
        type: string
      is_release:
        description: "Attach artifacts to Release"
        default: false
        type: boolean
      is_build:
        description: "Attach artifacts to Build"
        default: false
        type: boolean

jobs:
  build:
    name: Create Linux AppImage Build
    # Error: undefined symbol: g_once_init_enter_pointer
    # Build Linux app in the oldest Ubuntu for better compatibility
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - name: Patch Manifest
        run: |
          ASSET_URL="https://github.com/lyskouski/app-finance/releases/download/v${{ inputs.version }}/fingrom_Linux.tar.gz"
          curl -vLJO -H 'Accept: application/octet-stream' $ASSET_URL
          tar -xzf fingrom_Linux.tar.gz -C AppDir
          sh patch.sh -v "${{ inputs.version }}"
        working-directory: linux-appimage

      - name: Build AppImage
        uses: AppImageCrafters/build-appimage@v1
        env:
          UPDATE_INFO: gh-releases-zsync|lyskouski|app-finance|latest|*x86_64.AppImage.zsync
        with:
          recipe: AppImageBuilder.yml
        working-directory: linux-appimage

      - name: Rename output
        run: |
          APPIMAGE=$(find . -maxdepth 1 -name "*.AppImage" | head -n1)
          mv "$APPIMAGE" "Fingrom-${{ inputs.version }}-x86_64.AppImage"
        working-directory: linux-appimage

      - name: Add AppImage Artifact to Build
        if: inputs.is_build
        uses: actions/upload-artifact@v4
        with:
          name: Fingrom-${{ inputs.version }}-x86_64
          path: linux-appimage/Fingrom-${{ inputs.version }}-x86_64.AppImage

      - name: Add AppImage Artifact to Release
        if: inputs.is_release
        uses: actions/upload-release-asset@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ inputs.upload_url }}
          asset_path: linux-appimage/Fingrom-${{ inputs.version }}-x86_64.AppImage
          asset_name: Fingrom-${{ inputs.version }}-x86_64.AppImage
          asset_content_type: application/vnd.appimage
