// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions? get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
      // return windows;
      case TargetPlatform.linux:
      default:
        return null;
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-F5CBBZjskRbfqkeP1nPt7UUCuWQVy68',
    appId: '1:316045786606:web:e9346723741d371ad562ff',
    messagingSenderId: '316045786606',
    projectId: 'fingrom',
    authDomain: 'fingrom.firebaseapp.com',
    storageBucket: 'fingrom.firebasestorage.app',
    measurementId: 'G-ZLKVBF1H4V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBaT0FV9Xd46OZr4wcc_X44w1zpsaybiMo',
    appId: '1:316045786606:android:56767cb0c0a39bbfd562ff',
    messagingSenderId: '316045786606',
    projectId: 'fingrom',
    storageBucket: 'fingrom.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyByWAdeAUDluD-dlJHrt4Z1oyValCuFBpM',
    appId: '1:316045786606:ios:87bd828f023ae743d562ff',
    messagingSenderId: '316045786606',
    projectId: 'fingrom',
    storageBucket: 'fingrom.firebasestorage.app',
    iosClientId: '316045786606-d806bn8s90gj03nil8gooku2frptvrge.apps.googleusercontent.com',
    iosBundleId: 'com.tercad.fingrom',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyByWAdeAUDluD-dlJHrt4Z1oyValCuFBpM',
    appId: '1:316045786606:ios:87bd828f023ae743d562ff',
    messagingSenderId: '316045786606',
    projectId: 'fingrom',
    storageBucket: 'fingrom.firebasestorage.app',
    iosClientId: '316045786606-d806bn8s90gj03nil8gooku2frptvrge.apps.googleusercontent.com',
    iosBundleId: 'com.tercad.fingrom',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDj5sNiVmNi4x1PcL5ciYrX90n2VlMlOwY',
    appId: '1:316045786606:web:8cdba83e8f2fd15ad562ff',
    messagingSenderId: '316045786606',
    projectId: 'fingrom',
    authDomain: 'fingrom.firebaseapp.com',
    storageBucket: 'fingrom.firebasestorage.app',
    measurementId: 'G-4XJJ4TVMGE',
  );
}
